zend_extension=xdebug
; Xdebug configuration for development
; Mode can be: off, develop, coverage, debug, gcstats, profile, trace
xdebug.mode=develop,debug,coverage
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.start_with_request=trigger
xdebug.discover_client_host=true
xdebug.log=/tmp/xdebug.log
xdebug.idekey=VSCODE
